parameters:
#    debb_management.example.class: Debb\ManagementBundle\Example

services:
    debbconfig.twig.managementbundle_extension:
        class: Debb\ManagementBundle\Twig\Extension
        arguments:
            - "@service_container"
        tags:
            - { name: twig.extension }
