DebbConfigBundle:
    resource: "@DebbConfigBundle/Resources/config/routing.yml"

DebbManagementBundle:
    resource: "@DebbManagementBundle/Resources/config/routing.yml"

CIMPluploadBundle:
    resource: "@CIMPluploadBundle/Controller/"
    type:     annotation
    prefix:   /plupload

_imagine:
    resource: .
    type: imagine
